sonar.projectKey=techCamp-proyecto
sonar.projectName=techCamp-proyecto
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9001

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.git/**,**/*.min.js,**/*.map,**/sonar-export/**

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info